  type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
                #  will be installed and set up
  custom-flatpaks: # this section is optional
      # - Celluloid: io.github.celluloid_player.Celluloid
      # - Krita: org.kde.krita
    - com.brave.Browser                         
    - com.discordapp.Discord                    
    - com.github.tchx84.Flatseal                
    - com.google.Chrome                         
    - com.jetbrains.PyCharm-Community           
    - com.spotify.Client                        
    - com.usebottles.bottles                    
    - com.visualstudio.code
    - com.vscodium.codium                       
    - io.github.jonmagon.kdiskmark              
    - org.chromium.Chromium                     
    - org.filezillaproject.Filezilla            
    - org.gimp.GIMP                             
    - org.gnome.DejaDup                         
    - org.inkscape.Inkscape                     
    - org.libreoffice.LibreOffice               
    - org.mozilla.firefox                       
    - org.nmap.Zenmap                           
    - org.raspberrypi.rpi-imager                
    - org.remmina.Remmina                       
    - org.rncbc.qpwgraph                        
    - org.signal.Signal                         
    - org.videolan.VLC                          
    - org.wireshark.Wireshark                   
    - rest.insomnia.Insomnia                    
    - com.anydesk.Anydesk
