type: default-flatpaks
notify: true   # Send notification after install/uninstall is finished (true/false)
system:
  # If no repo information is specified, Flathub will be used by default
  repo-name: flathub
  repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
  install:
    #- org.gnome.Loupe
    #- one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
                                   # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08).
                                   # Only normal flatpak applications are (like Floorp Lightning web browser in this example).
                                   # Multiple install of same flatpaks with different branches is not supported.
user:
  repo-name: flathub-user
  repo-title: "Flathub (User)
  install:
    - com.brave.Browser                         
    - com.discordapp.Discord                    
    - com.github.tchx84.Flatseal                
    - com.google.Chrome                         
    - com.jetbrains.PyCharm-Community           
    - com.spotify.Client                        
    - com.usebottles.bottles                    
    - com.visualstudio.code
    - com.vscodium.codium                       
    - io.github.jonmagon.kdiskmark              
    - org.chromium.Chromium                     
    - org.filezillaproject.Filezilla            
    - org.gimp.GIMP                             
    - org.gnome.DejaDup                         
    - org.inkscape.Inkscape                     
    - org.libreoffice.LibreOffice               
    - org.mozilla.firefox                       
    - org.nmap.Zenmap                           
    - org.raspberrypi.rpi-imager                
    - org.remmina.Remmina                       
    - org.rncbc.qpwgraph                        
    - org.signal.Signal                         
    - org.videolan.VLC                          
    - org.wireshark.Wireshark                   
    - rest.insomnia.Insomnia                    
    - com.anydesk.Anydesk
